### PR TITLE
Account for time being added to unofficials

### PR DESCRIPTION
**Pull request by brianjmurrell**
https://review.lineageos.org/#/c/194050/
https://github.com/LineageOS/android_vendor_cm/commit/2179abe87e5f4bb79053160ce7cafca2c9fe3bc4

### CODE REVIEW

**Comment by julianxhokaxhiu** [comment]
May I ask what kind of change is this, and what are you trying to archive?

**Comment by brianjmurrell** [comment]
Did you look at the upstream changes referenced in the PR?  They show how a timestamp is now being included with the datestamp separated by an `_`.

`$(shell date -u +%Y%m%d_%H%M%S)` instead of `$(shell date -u +%Y%m%d)` for _UNOFFICIAL_ builds.

**Comment by julianxhokaxhiu** [comment]
Thanks. I didn't check it, as I saw your PR from mobile.

I'll test it tomorrow and I'll merge it asap.

**Comment by brianjmurrell** [comment]
@julianxhokaxhiu Cool.

**Comment by julianxhokaxhiu** [comment]
Released as 2.6.0 :) Thanks

**Comment by brianjmurrell** [comment]
Cheers!

**Pull request merged**
