### PR TITLE
Use a template instead of redirecting when visiting the web root

### PR DESCRIPTION
**Pull request by toolstack**
With Github builds not being local, simply redirecting to /builds isn't very useful, so instead create a landing page with customizable templates.

Also some readme cleanups.

### CODE REVIEW

**Review by julianxhokaxhiu — CHANGES_REQUESTED** [review]
Thank you very much for this PR!

In a nutshell, I'm all about this feature, but what about using [Twig](https://twig.symfony.com/) as a template engine? Should be relatively easy [to be integrated with FlightPHP](https://github.com/VincentLoy/flightphp-twig/blob/develop/index.php#L16-L18) if I'm not wrong.

If you could migrate those view to twig, I'd merge it right away.

Thank you!

**Comment by toolstack** [comment]
I used the built in template engine in Flight, didn't see a need to go outside of that.  Is there any significant benfit to using Twig?

**Comment by julianxhokaxhiu** [comment]
> I used the built in template engine in Flight, didn't see a need to go outside of that. Is there any significant benfit to using Twig?

I prefer to have a clear separation between code and HTML pages. I'm not a big fan of mixing PHP with HTML :) Also instead of the classic MVC, I prefer the MVVM approach, which is exactly what you are doing there.

**Comment by toolstack** [comment]
Ok, that doc was very old, but I got it working.

**Review by julianxhokaxhiu — APPROVED** [review]

**Comment by julianxhokaxhiu** [comment]
Fantastic work, thank you :)

**Pull request merged**
