### PR TITLE
Removed shell_exec instances and retrive timestamp from zip files (build.prop)

### PR DESCRIPTION
**Pull request by F0x06**
I suggest to use the timestamp contained in the zip file (ro.build.date.utc), because this can cause troubles in some circumstance, for example:

If you upload a file by hand on the server, the creation date of the file will be newer than the compillation date of the ROM and CMUpdater will believe that is a new version because CMUpdater compare the date contained in the build.prop (ro.build.date.utc).
# 

Removed shell_exec instances for md5 checksums of zip files, now uses only php's md5_file function, beacause  on the majority of php installations, shell_exec is disabled by default for security reasons.

### CODE REVIEW

**Comment by julianxhokaxhiu** [comment]
About the ro.build.date.utc is ok for me having it.

While for the removal of shell_exec piece of code, is already wrapped to be checked if you can execute a command at all, so if not, md5_file will be called. And it's fine this way. Giving users the flexibility to keep both the solutions: the one that can get their hands on the server, and the one that could not.

So, if you can only leave the lines of code for ro.build.date.utc i'll merge this. Thanks :)

**Comment by F0x06** [comment]
Hi, the problem is that your code check the presence of md5sum using 
shell_exec, in my case, this causes an error and the script stops because I 
not enabled shell_exec, you have a better idea :)? Cheers F0x

**Comment by julianxhokaxhiu** [comment]
Since the Safe Mode is almost deprecated by PHP itself (see http://php.net/manual/en/features.safe-mode.php) I would just patch the code with a snippet like this one http://stackoverflow.com/questions/5109064/php-safe-mode-in-server and you're done :)

But I'm not going to introduce that hack since PHP stable now is 5.5.

**Comment by F0x06** [comment]
The problem is not only the Safe Mod, but the disable_functions in php.ini, exec and shell_exec are disabled by default for security reasons. I patched the code with a verification as you asked that checks for Safe Mode and disabled_functions in php.ini :)

**Comment by ghost** [comment]
https://github.com/androidarmv6/CyanogenModOTA/commit/e94dd33b36340f37ac7e3df27fb123fc90a6c323

**Comment by julianxhokaxhiu** [comment]
Thanks @AndroidMeda I'll continue to merge your work :)
Since you provide the solution I'll close this ticket.

**Pull request closed without merging**
