### PR TITLE
URL and Changelog directory

### PR DESCRIPTION
**Pull request by syphyr**
These commits should fix the url to the build.zip and changelog.txt.  Also, it was necessary to place the changelog in a separate directory to prevent a conflict with the changelog.txt and the build.zip.

### CODE REVIEW

**Comment by julianxhokaxhiu** [comment]
Those commits looks good to me. Only one question: why did you separate the changelogs to a different folder? In my opinion they should live next to the ZIPs. So practically you're going to have this structure at the end:

```
/
-> builds
   -> full
      -> cm-13.0-20160407-NIGHTLY-hammerhead.zip
      -> cm-13.0-20160407-NIGHTLY-hammerhead.txt
   -> delta
       -> <delta_zip>.zip
       -> <delta_zip>.txt
```

Just like it is in the official CyanogenMod OTA Service.

To me feels more confortable, but I'm open to new opinions :) Thanks again for the PR

**Comment by syphyr** [comment]
The changelogs are separated to a different folder because the REST server gives an internal error when the changelog is in the same directory as the zip file. This fixes an internal parsing error that occurs when both files are in one directory.

**Comment by syphyr** [comment]
This is the error that occurs when the changelog.txt (cm-13.0-20160407-NIGHTLY-hammerhead.txt) and build.zip (cm-13.0-20160407-NIGHTLY-hammerhead.zip) are both located in builds/full/ like you posted above.  I could not figure out why the changelog.txt and build.zip are conflicting in builds/full/ when they both exist there at the same time.  I assume it is a parsing problem because they both have the same name, besides different extensions.

<h1>500 Internal Server Error</h1><h3>file_get_contents(zip:///var/www/html/CyanogenModOTA/builds/full/cm-13.0-20160402-NIGHTLY-awifi.txt#system/build.prop): failed to open stream: operation failed (2)</h3><pre>#0 [internal function]: flight\Engine->handleError(2, 'file_get_conten...', '/var/www/html/C...', 64, Array)
#1 /var/www/html/CyanogenModOTA/src/Helpers/Build.php(64): file_get_contents('zip:///var/www/...')
#2 /var/www/html/CyanogenModOTA/src/Helpers/Builds.php(130): JX\CmOta\Helpers\Build->__construct('cm-13.0-2016040...', '/var/www/html/C...')
#3 /var/www/html/CyanogenModOTA/src/Helpers/Builds.php(49): JX\CmOta\Helpers\Builds->getBuilds()
#4 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/core/Loader.php(123): JX\CmOta\Helpers\Builds->__construct()
#5 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/core/Loader.php(80): flight\core\Loader->newInstance('\JX\CmOta\Helpe...', Array)
#6 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/Engine.php(69): flight\core\Loader->load('builds', true)
#7 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(191): flight\Engine->__call('builds', Array)
#8 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(191): flight\Engine->builds()
#9 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/Flight.php(76): flight\core\Dispatcher::invokeMethod(Array, Array)
#10 /var/www/html/CyanogenModOTA/src/CmOta.php(97): Flight::__callStatic('builds', Array)
#11 /var/www/html/CyanogenModOTA/src/CmOta.php(97): Flight::builds()
#12 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(160): JX\CmOta\CmOta->JX\CmOta{closure}()
#13 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(143): flight\core\Dispatcher::callFunction(Object(Closure), Array)
#14 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/Engine.php(313): flight\core\Dispatcher::execute(Object(Closure), Array)
#15 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(191): flight\Engine->_start()
#16 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array)
#17 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#18 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/Engine.php(64): flight\core\Dispatcher->run('start', Array)
#19 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(191): flight\Engine->__call('start', Array)
#20 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(191): flight\Engine->start()
#21 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/Flight.php(76): flight\core\Dispatcher::invokeMethod(Array, Array)
#22 /var/www/html/CyanogenModOTA/src/CmOta.php(80): Flight::__callStatic('start', Array)
#23 /var/www/html/CyanogenModOTA/src/CmOta.php(80): Flight::start()
#24 /var/www/html/CyanogenModOTA/index.php(35): JX\CmOta\CmOta->run()
#25 {main}</pre>

**Comment by julianxhokaxhiu** [comment]
That's a missing check in an internal call to get the build.prop information, I was assuming to work always with ZIPs but I forgot ( the period when I wrote the code ) that also TXTs were living there.

I'll then patch everything in the right way this weekend then :) so I can finally push everything into Packagist

**Comment by julianxhokaxhiu** [comment]
Ok see version 2.0.3 :) Sorry that I didn't merge it, but I did it myself a little bit more cleaner!

**Comment by syphyr** [comment]
I'm still getting an internal error with the latest version. If I move the changelog.txt to a separate directory, then the server does not get that internal error. There is still a conflict with the file names with different extensions.

**Comment by julianxhokaxhiu** [comment]
Since I'm at work right now, I could not really test it. Can you please provide a log?

**Comment by syphyr** [comment]
<h1>500 Internal Server Error</h1><h3>Invalid argument supplied for foreach() (2)</h3><pre>#0 /var/www/html/CyanogenModOTA/src/Helpers/Build.php(263): flight\Engine->handleError(2, 'Invalid argumen...', '/var/www/html/C...', 263, Array)
#1 /var/www/html/CyanogenModOTA/src/Helpers/Build.php(71): JX\CmOta\Helpers\Build->getBuildPropValue('ro.build.versio...')
#2 /var/www/html/CyanogenModOTA/src/Helpers/Builds.php(130): JX\CmOta\Helpers\Build->__construct('cm-13.0-2016040...', '/var/www/html/C...')
#3 /var/www/html/CyanogenModOTA/src/Helpers/Builds.php(49): JX\CmOta\Helpers\Builds->getBuilds()
#4 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/core/Loader.php(123): JX\CmOta\Helpers\Builds->__construct()
#5 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/core/Loader.php(80): flight\core\Loader->newInstance('\JX\CmOta\Helpe...', Array)
#6 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/Engine.php(69): flight\core\Loader->load('builds', true)
#7 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(191): flight\Engine->__call('builds', Array)
#8 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(191): flight\Engine->builds()
#9 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/Flight.php(76): flight\core\Dispatcher::invokeMethod(Array, Array)
#10 /var/www/html/CyanogenModOTA/src/CmOta.php(97): Flight::__callStatic('builds', Array)
#11 /var/www/html/CyanogenModOTA/src/CmOta.php(97): Flight::builds()
#12 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(160): JX\CmOta\CmOta->JX\CmOta{closure}()
#13 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(143): flight\core\Dispatcher::callFunction(Object(Closure), Array)
#14 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/Engine.php(313): flight\core\Dispatcher::execute(Object(Closure), Array)
#15 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(191): flight\Engine->_start()
#16 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array)
#17 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#18 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/Engine.php(64): flight\core\Dispatcher->run('start', Array)
#19 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(191): flight\Engine->__call('start', Array)
#20 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(191): flight\Engine->start()
#21 /var/www/html/CyanogenModOTA/vendor/mikecao/flight/flight/Flight.php(76): flight\core\Dispatcher::invokeMethod(Array, Array)
#22 /var/www/html/CyanogenModOTA/src/CmOta.php(80): Flight::__callStatic('start', Array)
#23 /var/www/html/CyanogenModOTA/src/CmOta.php(80): Flight::start()
#24 /var/www/html/CyanogenModOTA/index.php(35): JX\CmOta\CmOta->run()
#25 {main}</pre>

**Comment by julianxhokaxhiu** [comment]
Sorry for the delay. Today I had a chance to look at it and do a final fix! Look at v2.0.4 :)

Please refer if any other bug found! Greets

**Pull request closed without merging**
