### PR TITLE
Fix delta builds.

### PR DESCRIPTION
**Pull request by emfox**
since $ret here is empty, array_merge will not work.
and fix a typo too so the delta builds is ok now.

### CODE REVIEW

**Comment by julianxhokaxhiu** [comment]
Although the misstype in fact is wrong and your commit is fine, I cannot accept the other one because on PHP merging two array, doesn't matter if they are empty or not, they will merge. That code was tested and Is working.

But if you would like, you can also test this simple code here:

``` php
<?php
  $ret = array();

  $test = array( '1', '2', '3' );

  var_dump( array_merge( $ret, $test ) );
?>
```

It will merge fine without any sort of issue :) If you can redo a PR only for the misstype I'll be more than happy to merge that!

**Comment by emfox** [comment]
sorry, I'm not that familiar with php, and I read the manual of array_merge, found that it just return new array without touching original ones. so here's the new fix, and have been splitted into too pieces.

**Comment by julianxhokaxhiu** [comment]
No problem :) I fixed it myself on 2.0.3, please take a look at it. Feedbacks are welcome!

**Comment by emfox** [comment]
this hasn't been merged:
https://github.com/emfox/CyanogenModOTA/commit/de4dd7df98d4cca7dd056c774136e21d2ab7c2f0

**Comment by julianxhokaxhiu** [comment]
You're right, I have anyway to do another release, later I'll merge also that :)

**Comment by julianxhokaxhiu** [comment]
Now it is! Sorry again :) Look for v2.0.4

**Pull request closed without merging**
